### ISSUE TITLE
How to pass data using the constructor arguments???

### ISSUE THREAD

**Issue by steveyout** [verful/adonis-notifications#2]
How to pass data using the constructor arguments???

i.e ```await user?.notifyLater(new Notification(data));```

then in notification class ```constructor (private user: User) {
    super()
  }```

**Comment by arthur-er** [comment]
Just like you said, you just need to remove the `super()` call, as notification classes not extends a base notification class.

Be aware that data passed to `notifyLater` will be serialized, so passing in a model may not work as expected, as the model will be serialized.

**Comment by steveyout** [comment]
ok,,Thanks
