### ISSUE TITLE
Is this a dead repo? 

### ISSUE THREAD

**Issue by TDodgeCo** [verful/adonis-notifications#22]
Just putting this issue here in an effort to save some future dev the effort and energy of trying to work through this disaster of a package. If this issue is still up, this package is still broken.

Docs are either woefully out of date or incomplete. Type errors and SQL errors all over the place.

**Comment by arthur-er** [comment]
Type errors are gone in 2.1.0, please update and re-run `node ace configure`

If there's missing docs, please open a PR or tell me what's wrong here. There should be no SQL errors if you follow the docs accordingly.
