### ISSUE TITLE
Cannot process unregistered relationship 'notifications'

### ISSUE THREAD

**Issue by HasanAshab** [verful/adonis-notifications#42]
This error occurs only when
1. sending with database driver
2. notifiable model has multiple mixins used in

The main reason of the error is orm decorators from mixins don't work  properly. 

I can make a PR to resolve the issue

**Comment by arthur-er** [comment]
Please, do it

**Comment by maukoese** [comment]
I'm still getting this error even after updating to 2.3.0

**Comment by HasanAshab** [comment]
> I'm still getting this error even after updating to 2.3.0

share your model

**Comment by maukoese** [comment]
![Here you go](https://github.com/verful/adonis-notifications/assets/14233942/e1c38c50-0e7f-448b-8aa9-4f583101e12c)

It was working fine all of last year, until last week.

**Comment by HasanAshab** [comment]
Keep only BaseModel and Notifiable. then see if prob remains

**Comment by maukoese** [comment]
Removing everything else and only keeping Base Model and Notifiable works.

I've realized the SoftDeletes and Authorizable mixins are the ones causing the issues

<img width="977" alt="Screenshot 2024-02-03 at 08 22 45" src="https://github.com/verful/adonis-notifications/assets/14233942/eb3bb3e3-e843-4f26-b14b-3f5ca18d03b0">

**Comment by maukoese** [comment]
Ah, I have fixed it by changing the order and moving the Notifiable mixin app. All working now.

![notifiable](https://github.com/verful/adonis-notifications/assets/14233942/454fba99-6e36-4a9b-b15b-8bc7c2417edc)
