### ISSUE TITLE
No Exception Handler

### ISSUE THREAD

**Issue by fredrickreuben** [verful/adonis-notifications#5]
Thank you for this great plugin, I really want to know if their is away i can capture response from message channels and use them inside notification class. USE CASE i have an sms channel that uses external api to send message, I want to capture and use api responses inside notification class.

**Comment by arthur-er** [comment]
That's not the intended use of the notification class, you should do that on the channel level, either by hard-coding it or emitting a event.

**Comment by fredrickreuben** [comment]
thank you so much am now getting the following when i create a try to use custom channel "sms" driver is not supported by "Notification"

**Comment by arthur-er** [comment]
Can you provide a reproduction repo with your channel?
